---
title: "Analysis"
output: html_notebook
---

```{r Load packages, include=FALSE}
library(tidyverse)
library(tidymodels)
library(skimr)
library(lubridate)  # for handling dates and time
```
```{r Define functions, include=FALSE}
load_bci_data <- function(fileNamePattern, columns) {
  # list all files in data folder, that end with "Game.csv"
  list.files(recursive=TRUE, path = "./data", pattern = fileNamePattern, full.names = T) %>%
    tibble(filename = .) %>%
    # load the contents of each CSV file
    mutate(file_contents = map(filename, ~read_csv(file.path(.), na = "NULL", col_types = columns))) %>%
    # extract the nested columns into a flat table
    unnest(cols=-filename) %>%
    # extract the participant label and the condition ("Level") from the file path
    separate(col=filename,sep="/",into=c("start","folder","Participant","Level","filename")) %>%
    # remove the leading "P" from participant label, e.g. P10 -> 10
    mutate(
      Participant=as.numeric(str_replace(Participant,"P","")), Level=as.factor(Level),
    ) %>%
    dplyr::group_by(Participant, Level) %>%
    mutate(
      vis_t_time = as.POSIXlt(Timestamp, format = "%Y-%m-%d %H:%M:%OS"),
      Timestamp = seconds(vis_t_time)) %>%
    ungroup()
}
```

## BCI - Continuous and Discrete Input

```{r Load pre-experiment questionnaire data, echo=FALSE, results='hide'}
preQuestionnaire <- as_tibble(read.csv(file.path("./data","preQuestionnaire.csv"),stringsAsFactors=FALSE)) %>%
  mutate_if(is.character, stringr::str_replace_all, pattern = " ", replacement = "_")
preQuestionnaire <- preQuestionnaire %>%
  pivot_longer(cols = -X, names_to = "Participant") %>%
  mutate_if(is.character, stringr::str_replace_all, pattern = " ", replacement = "_") %>%
  mutate_if(is.character, stringr::str_replace_all, pattern = "P", replacement = "") %>%
  mutate(Participant = as.numeric(Participant)) %>%
  pivot_wider(names_from = X)

```

```{r Load post-experiment questionnaire data, echo=FALSE, results='hide'}
postQuestionnaire <- as_tibble(read.csv(file.path("./data","postQuestionnaire.csv")))
orderNumber <- rep(c(1,2,2,1),10)
postQuestionnaire <- cbind(postQuestionnaire, orderNumber)
```

```{r Load game data, echo=FALSE, results='hide'}
game_columns = cols(
  .default = col_double(),
  Event = col_character(),
  Timestamp = col_datetime(format = ""),
  SessionID = col_character(),
  Email = col_character(),
  BCIState = col_character(),
  InputWindow = col_character(),
  GameState = col_character(),
  TrialResult = col_character(),
  TrialGoal = col_character(),
  BCIThresholdBuffer = col_character()
)
game <- load_bci_data("*Game.csv", game_columns)
game <- game %>%
  # convert time to a proper Timestamp object
  dplyr::group_by(Participant, Level) %>%
  mutate(
    GameIsOn = ifelse(Event == "GameRunning", 1, 0),
    GameIsOn = cumsum(GameIsOn)) %>%
    arrange(Participant,Level,Timestamp) %>%
    dplyr::mutate(InputWindowNum = dplyr::lag(ifelse(Event == "GameDecision", 1, 0),default=0)) %>%
    dplyr::mutate(InputWindowNum = cumsum(InputWindowNum)) %>%
    ungroup()
game <- game %>%
  select(Participant, Level, InputWindowNum,Timestamp) %>%
  dplyr::group_by(Participant, Level, InputWindowNum) %>%
  dplyr::summarise(StartTime = min(Timestamp)) %>%
  right_join(game) %>%
  mutate(TimeSinceIWstart = ifelse(TrialResult == "AccInput",Timestamp - StartTime,NA))

gameSummary <- game %>%
  dplyr::mutate(successes = ifelse(TrialResult == "AccInput", 1, 0)) %>%
  dplyr::group_by(Participant, Level) %>%
  dplyr::summarize(accPerc = sum(successes,na.rm = TRUE) / max(InputWindowNum), activateDelay = mean(TimeSinceIWstart,na.rm = TRUE))

# Filter game columns, add columns here on need-only basis
game <- game[c("Participant", "Level", "Timestamp", "GameIsOn", "InputWindowNum", "BCIConfidence")]
```

```{r Load meta data, echo=FALSE, results='hide'}
meta_columns = cols(
  SessionID = col_character(),
  Timestamp = col_datetime(format = ""),
  Framecount = col_double(),
  Email = col_character(),
  DeviceID = col_character(),
  FabInputTrials = col_double(),
  AccInputTrials = col_double(),
  RejInputTrials = col_double(),
  Trials = col_double(),
  InterTrialInterval_sec = col_double(),
  InputWindow_sec = col_double(),
  noInputReceivedFabAlarm_sec = col_double(),
  FabAlarmVariability_sec = col_double(),
  ConfidenceThreshold = col_double(),
  BCIProcessingMode = col_character(),
  ConsecutiveThresholdBufferSize = col_double()
)

meta <- load_bci_data("*Meta.csv", meta_columns)

# Filter meta columns, add columns here on need-only basis
meta <- meta[c("Participant", "Level", "Timestamp")]
```

```{r Load sample data, echo=FALSE, results='hide'}
sample_columns = cols(
  Event = col_character(),
  Timestamp = col_datetime(format = ""),
  Framecount = col_double(),
  SessionID = col_character(),
  Email = col_character(),
  BCIConfidence = col_double(),
  BCIState = col_character()
)
sample <- load_bci_data("*Sample.csv", sample_columns)

# Filter meta columns, add columns here on need-only basis
sample <- sample[c("Participant", "Level", "Event", "Timestamp", "BCIConfidence")]
```

```{r Merge all data, echo=FALSE, results='hide'}
gameSummary <-gameSummary %>% merge(postQuestionnaire) %>% merge(preQuestionnaire)
gameSummary <- merge(gameSummary,postQuestionnaire)
```

```{r Overview}
gameSummary %>%
  select(-Participant) %>%
  group_by(Level) %>%
  skim()

postQuestionnaire %>%
  select(-Participant) %>%
  group_by(Level) %>%
  skim()
```